### ISSUE TITLE
it does not build

### ISSUE THREAD

**Issue by therealmarv** [nuxt-community/typescript-template#14]
![image](https://user-images.githubusercontent.com/1050582/32601697-3ab8be3a-c54c-11e7-888a-d3ae4d3b87e9.png)

see screenshot. thx.

**Comment by KleinMaximus** [comment]
I have the same problem :(

**Comment by jycy** [comment]
Try changing "query" with "options"

**Comment by igorszymanski** [comment]
Then this happens:

` ERROR  Failed to compile with 2 errors

These dependencies were not found:

* ~components/Card.vue in ./node_modules/ts-loader?{"appendTsSuffixTo":["//.vue$"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
* ~plugins/axios in ./api/people.ts

To install them, you can run: npm install --save ~components/Card.vue ~plugins/axios`

**Comment by qm3ster** [comment]
fixed in #27
