### ISSUE TITLE
Running an instance on the custom port is not working correctly

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/typescript-template#21]
I want to run Nuxt TS project on the custom port, say localhost:3333. According to Nuxt official documentation in order to do so, I need to specify Nuxt settings inside options object in my package.json file like so:
"config": {
 "nuxt": {
   "port": "3333"
 }
}
but once done I'm starting to get an error:

`Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)`
After some investigation I've also changed env.baseUrl to also be on the 3333 port like so:
`env: {
    baseUrl: process.env.BASE_URL || 'http://localhost:3333'
  }`

but such approach is not optimal cos I have to specify that port in 2 places. How can I make the setup respect the port setting that is specified in config.json file?

**Comment by qm3ster** [comment]
If you are using the package.json method, it will be available in `process.env.npm_package_config_nuxt_port` so
```js
const port =
	process.env.PORT || process.env.npm_package_config_nuxt_port || 3000

const baseUrl = process.env.BASE_URL || `http://localhost:${port}`

module.exports={
	env: {
		baseUrl
	}
}
```
should solve your case.
Maybe I should add it to the template.

Have you tried the `cross-env PORT=3333 nuxt`  method? I hear it's quite spicy this time of the year.

**Comment by AndrewBogdanovTSS** [comment]
> Have you tried the cross-env PORT=3333 nuxt method?

Yeah, I understand that such option exists, yet I don't find it to be optimal due to a cross-env dependency. 
When I was using regular Nuxt.js starter template  I was able to pass a `nuxt --port=3333` parameter directly without the need to install any additional dependencies (which seems logical to me) but in this TS starter template, I'm unable to use the same approach for some reason.

> Maybe I should add it to the template.

that would be great to have since package.json port specification exists in Nuxt.js docs and I think new templates shouldn't break existing Nuxt functionality but rather extend it

**Comment by qm3ster** [comment]
It's somewhat new to the (nuxt) specification, and I am not sure how I feel about it.
`npm_package_config_**` is only populated if a package manager was used to invoke node, straight `./server.js` or `node server.js` would lead to that being unset.
I guess it could be `server.js`s responsibility to `require('./package.json')` in that case.
Yeah, I will probably add it today.

@AndrewBogdanovTSS do you have any thoughts about the npm problem?

**Comment by AndrewBogdanovTSS** [comment]
> Yeah, I will probably add it today.

Thanks a lot for your help, @qm3ster 

> do you have any thoughts about the npm problem?

no, I keep investigating it

**Comment by qm3ster** [comment]
Okay, so first nuxt does the "right thing" (according to us here):
https://github.com/nuxt/nuxt.js/blob/c415a679e40730d780bfe8b37f1544bbbf23e730/bin/nuxt-dev#L86
and then completely ignores it and just uses config:
https://github.com/nuxt/nuxt.js/blob/c415a679e40730d780bfe8b37f1544bbbf23e730/bin/nuxt-dev#L102
:thinking::thinking::thinking:
Sounds like I am going to PR nuxt.

**Comment by AndrewBogdanovTSS** [comment]
Isn't it back in use on line 137?
https://github.com/nuxt/nuxt.js/blob/c415a679e40730d780bfe8b37f1544bbbf23e730/bin/nuxt-dev#L137

**Comment by qm3ster** [comment]
Yeah, it uses it for the server, but uses options for the innards. They never touch.

**Comment by qm3ster** [comment]
found where they are finally defaulted to `'localhost:3000'`:
https://github.com/nuxt/nuxt.js/blob/8fcef54a23932d7f728fba535e7bb117d69d56e8/lib/core/nuxt.js#L139
