### ISSUE TITLE
Example without class-style components

### ISSUE THREAD

**Issue by ay13** [nuxt-community/typescript-template#30]
This example uses class-style components and property decorators. Is there an example without those?

From vue-cli 3 default not using the class-style components:
```html
<template>
  <div class="home">
    <img src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src

export default Vue.extend({
  name: 'home',
  components: {
    HelloWorld,
  },
});
</script>
``` 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c27">#c27</a>)</em></sub></div>

**Comment by qm3ster** [comment]
There isn't an option or a separate template for that at the moment, but in any `.vue` file you can just do what you've written. The idea is just that class-style components provide better type information.

**Comment by AndrewBogdanovTSS** [comment]
@ay13 what issues do you get when compiling code provided in your first post?

**Comment by ay13** [comment]
No issue with the above example since it has no types in it. The below will give you the error `Unexpected token`

```html
<template>
  <div class="home">
    <img src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src

const msg: string = 'Welcome to the site!';

export default Vue.extend({
  name: 'home',
  components: {
    HelloWorld,
  },
  data() {
    return {
      message: msg,
    };
  },
});
</script>
```

**Comment by qm3ster** [comment]
Yeah, doesn't happen for me.
Did you create the `@` alias? `tsconfig.json` in this template only specifies `~/`

**Comment by qm3ster** [comment]
Is this an error in your editor or in the terminal when running dev?
Because if it's the editor you probably have something like eslint happening.
Did it not complain about the experimental decorator originally?

**Comment by hmsk** [comment]
Closes since the issue is stale.
And the future of Vue will take "class-based component natively", so don't need to care about "object-based component" much.
https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf
