### ISSUE TITLE
Unable to transition to process.client from context.isClient

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/typescript-template#33]
Since the project was updated to Nuxt v. 1.3.0 I started getting a deprecation warning inside my middleware functions:
`context.isClient has been deprecated, please use process.client instead.`
the funny part is that I can't change my code to use `process.client` instead because of TS error:
`TS2339: Property 'client' does not exist on type 'Process'.`
so it seems like this change was made without TS in mind. How can this typing issue be fixed?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c25">#c25</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Seems like this is something where you have to do the nasty thing known as declaration merging :(
```ts
declare namespace NodeJS {
  export interface Process {
    client: boolean
    server: boolean
  }
}
declare var process: NodeJS.Process
```
dropping the above into your index.d.ts seems to fix it.

**Comment by AndrewBogdanovTSS** [comment]
Will this issue be fixed on the Nuxt level? Should I log a bug in a related repo?

**Comment by kevinmarrec** [comment]
@husayt You're probably missing `"@nuxt/vue-app-edge"` in `tsconfig.json`.
Here is my current `tsconfig.json` :
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": [
      "esnext",
      "esnext.asynciterable",
      "dom"
    ],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ]
    },
    "types": [
      "@types/node",
      "@nuxt/vue-app-edge"
    ]
  }
}

```

It will bee soon become
```json
{
  "extends": "nuxt-ts-edge"
}
```

So that everything work out of the box.

**Comment by husayt** [comment]
Thanks @kevinmarrec. 

I tried ` "types": ["@types/node", "@nuxt/vue-app-edge"]` and it didn't work.
and then i changed it to 
` "types": ["@types/node", "nuxt-ts-edge/node_modules/@nuxt/vue-app-edge"]` and that worked.
It's bit ugly bot does the job. Might be a good idea to add @nuxt to peer/high level dependency of `nuxt-ts-edge`.

**Comment by AndrewBogdanovTSS** [comment]
Is it valid to close this bug until it's really fixed in a stable version of Nuxt?

**Comment by husayt** [comment]
@kevinmarrec  indeed damn NPM. Thank you very much.
By the way, I had finally some time to port hackernews to TS and commit it [here](https://github.com/nuxt-community/hackernews-nuxt-ts)

Your feedback will be most appreciated.

**Comment by kevinmarrec** [comment]
@husayt Will give my feedback when I'll find some time ;) Thanks for working on it !

**Comment by bitdom8** [comment]
Hi guys, any update? Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
