### ISSUE TITLE
Change api to middleware

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/typescript-template#35]
That's just a suggestion. Since we don't have any example of a middleware inside a template but we use an undocumented `api` folder which is just a discrepant addition in my opinion. Why not use `middleware` as Nuxt intended? `api/people.ts` can be placed in middleware folder and rewritten as such:
```
export default async function({store, error, redirect}){
    if(process.client) return;
    await store.dispatch('getPeople')
}
```
and in the store actions:
```
async getPeople({commit}){
            commit('setPeople', await axios.get('/random-data.json').data.slice(0,3));
    }
```
and in `nuxt.config.js` module.exports object
```
router: {
    middleware: 'people'
  },
```
this way we can showcase how middleware function can be used in the template that might be beneficial for a lot of users

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c30">#c30</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
I've created a PR to reflect that change #36

**Comment by qm3ster** [comment]
Sorry, I reviewed the PR before seeing this.
Like I said, I think this is a poor use of middleware and will confuse people.
Middleware in ts works exactly the same as without, so we don't need to exercise it.
Perhaps if we give typings for the arguments of the middleware function, it will be more useful.

Still, I think we can do much better than the example.

As for the api folder, I thought it was a decent way of abstracting away `axios` (someone's api might be `firebase-client`, etc.) and the correct place to typecheck the returned values and handle network errors, returning the store or other caller a parsed data promise.

**Comment by AndrewBogdanovTSS** [comment]
I guess this issue can be closed
