### ISSUE TITLE
Integrate with create nuxt app

### ISSUE THREAD

**Issue by pkej** [nuxt-community/typescript-template#38]
To get one step to select between JS and TS. [Create-nuxt-app](https://github.com/nuxt-community/create-nuxt-app)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c31">#c31</a>)</em></sub></div>

**Comment by hmsk** [comment]
This issue ended up being resolved by https://github.com/nuxt/create-nuxt-app/pull/328 👏
