### ISSUE TITLE
Saperate the script in vue files to .ts files.

### ISSUE THREAD

**Issue by hannanmumtaz** [nuxt-community/typescript-template#39]
Hi guys.

Is it pobbile to split .vue files under /pages and keep the script in .ts file and the template in .vue files.

am trying to split the html and the script part.

the /pages can have
/pages/index.vue
/pages/index.ts

index.vue - can have reference to script

<template>
  <section class="pa4 code">
    <div class="bg-white-90 pa4">
      <div class="f1">Nuxt TypeScript Starter</div>
      <div class="f3">Selected Person: {{selectedPerson.first_name}} {{selectedPerson.last_name}} is #{{selected}}</div>
      
    </div>
    <div class="flex flex-wrap ph2 justify-between bg-white-80">
      <div :key="person.id" v-for="person in people">
        <Card :person="person"></Card>
      </div>
    </div>
  </section>
</template>
**<script src="./index.ts"></script>**

is the above currently possible ?

**Comment by qm3ster** [comment]
Typically yes, have you tried it already?
I think you have to still set `lang` tho.
```vue
<script lang="ts" src="./index.ts" />
```

**Comment by hannanmumtaz** [comment]
ah, lang="ts" did the job, i was thinking it will infer the type from the filename, all good now, thanks for your help @qm3ster :)

**Comment by qm3ster** [comment]
I imagine that could be the case, but apparently it isn't.
Not mentioned anywhere either: [[1]](https://github.com/vuejs/vue-loader/blob/e637c886b6d0b029954f1b18dc0c101acfc3f48f/docs/en/configurations/pre-processors.md) [[2]](https://github.com/vuejs/vue-loader/blob/7fb1cd84a006b631102481a810cf201cdefe9e36/docs/en/configurations/advanced.md) [[3]](https://vue-loader.vuejs.org/en/start/spec.html#src-imports)
Maybe file an issue or PR the documentation if you have the time.

**Comment by lsotoangeldonis** [comment]
Hi, I'm having an issue with the method suggested,

```
<script lang="ts" src="./navbarCategoriesComponent.ts"></script>
<style lang="scss" src="./navbarCategoriesComponent.scss" scoped></style>

    <template>
        <div class="container">HELLO</div>
    </template>

```

This is giving me this error:

![image](https://user-images.githubusercontent.com/38225539/70340658-33c7b400-181f-11ea-807f-cf493d31dbbb.png)

thanks in advance.

**Comment by qm3ster** [comment]
@lsotoangeldonis what's in `navbarCategoriesComponent.ts`?
