### ISSUE TITLE
How to integrate some test tool eg Ava/Karma/Tape etc.

### ISSUE THREAD

**Issue by velidan** [nuxt-community/typescript-template#41]
Hi. Could you, please, provide some tutorial how to integrate any of these tools into this nuxt-project? I have spent a lot of time to try to configure but it doesn't work at all. 

Many thanks for any help. 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c34">#c34</a>)</em></sub></div>

**Comment by brantwills** [comment]
Would be interested in this as well - I had some success with jest, but hit some walls:
https://github.com/brantwills/nuxt-ts-jest-starter-template
