### ISSUE TITLE
Cannot deploy to Netlify

### ISSUE THREAD

**Issue by salvadornico** [nuxt-community/typescript-template#42]
Hi, I'm encountering an error when trying to deploy this template to Netlify.

This error appears in the deployment log, although it still completes and marks the deployment as succesful:
![screenshot from 2018-03-02 11-34-41](https://user-images.githubusercontent.com/25360297/36882353-51eccd60-1e0e-11e8-99bf-ada50f556a15.png)

After deployment, this is all that appears when following the genrated URL (https://hardcore-curie-c8f6ae.netlify.com)
![screenshot from 2018-03-02 11-35-20](https://user-images.githubusercontent.com/25360297/36882383-763f76a4-1e0e-11e8-972a-a328fcc87103.png)

I'm not sure if there's something wrong with the template itself or my deployment.

Steps to recreate:

1. `$ vue init nuxt-community/typescript-template my-project` OR clone my repo of the same: `$ git clone https://github.com/salvadornico/nuxt-ts-test.git`
2. Add to Github as a new repository
3. Create new site on Netlify, connecting this new repo
4. For deployment settings: `yarn generate` as build command, `dist` as publish directory
5. Deploy site

Thanks for the help!

**Comment by salvadornico** [comment]
Additional info: A similar error also appears on my local machine when running `$ yarn generate`:
![screenshot from 2018-03-02 18-03-02](https://user-images.githubusercontent.com/25360297/36893763-36e6add4-1e44-11e8-8fd9-bde024f2a160.png)

**Comment by qm3ster** [comment]
You clearly have some kind of server (api?) when running `nuxt dev`. Generate doesn't actually start your app, so your (local) server isn't accessible. One quick hack solution would be to do `nuxt build && nuxt start` in one terminal and then `nuxt generate` in another.

**Comment by qm3ster** [comment]
Oh, muh dude, it's that gosh darn example project!
In this case, the "api" is just the .json served from the static directory.l
You probably wouldn't have anything like that in real life.

**Comment by salvadornico** [comment]
Looks like that was the issue. I sidestepped the whole JSON step and just copied the data straight into the Vuex store.

Thanks a lot, this really helped me better understand what's going on in both Nuxt and Netlify!
