### ISSUE TITLE
vue-dev-tools do not work

### ISSUE THREAD

**Issue by sobolevn** [nuxt-community/typescript-template#46]
### Version

[6af12b03f798c7a0a50c209a98a833ac57753402](https://github.com/nuxt-community/typescript-template/releases/tag/6af12b03f798c7a0a50c209a98a833ac57753402)

### Reproduction link

[https://github.com/nuxt-community/typescript-template](https://github.com/nuxt-community/typescript-template)

### Steps to reproduce

Before running make sure that `vue-dev-tools` is installed in your browser.

1. Run `npx vue-cli init nuxt-community/typescript-template my-ts-project`
2. Run `npm install`
3. Run `npm run dev` and visit `localhost:3000`
4. Open dev tools

### What is expected ?

I expect that my state, my components, and my event will be shown.

### What is actually happening?

![Снимок экрана 2018-04-14 в 10.45.39.png](https://cmty.s3.eu-west-1.amazonaws.com/89532162/e5e7d120-3fb7-11e8-a5f2-37162c111054.png)
![Снимок экрана 2018-04-14 в 10.45.43.png](https://cmty.s3.eu-west-1.amazonaws.com/89532162/e39359d0-3fb7-11e8-a5f2-37162c111054.png)
Nothing is shown. All tabs are empty.
![Снимок экрана 2018-04-14 в 10.45.49.png](https://cmty.s3.eu-west-1.amazonaws.com/89532162/e14b3e90-3fb7-11e8-a5f2-37162c111054.png)

### Additional comments?

Other apps work fine.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c36">#c36</a>)</em></sub></div>

**Comment by sobolevn** [comment]
That's what happens inside "Console" tab.
![2018-04-14 10 47 14](https://user-images.githubusercontent.com/4660275/38765815-3e861116-3fd1-11e8-9deb-23bd21bafbb3.png)

**Comment by jalcine** [comment]
What is Vue/Nuxt running under?

**Comment by sobolevn** [comment]
I used this commit of the template https://github.com/nuxt-community/typescript-template/releases/tag/6af12b03f798c7a0a50c209a98a833ac57753402

**Comment by hmsk** [comment]
![image](https://user-images.githubusercontent.com/85887/50755929-6af8a400-120f-11e9-86ca-b8346ffc89a6.png)

Currently, it looks working. Reopen if you still have the same problem 🙏
