### ISSUE TITLE
Update TypeScript version

### ISSUE THREAD

**Issue by tamanyan** [nuxt-community/typescript-template#53]
### What problem does this feature solve?

Use TypeScript 3 in this template

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/typescript-template/issues/c43">#c43</a>)</em></sub></div>

**Comment by babakness** [comment]
And support Nuxt 2!

**Comment by hmsk** [comment]
It's now running with TS3.2.2
