### ISSUE TITLE
Not compatible with nuxt 2.0.0

### ISSUE THREAD

**Issue by P4sca1** [nuxt-community/typescript-template#54]
### Version

[2.0.0](https://github.com/typescript-template/releases/tag/2.0.0)

### Reproduction link

[https://github.com/nuxt-community/typescript-template](https://github.com/nuxt-community/typescript-template)

### Steps to reproduce

```
vue init nuxt-community/typescript-template my-project
cd my-project
npm i -S nuxt@2.0.0
npm install
npm run dev
```

### What is expected ?

Working nuxt.js installation with TypeScript support.

### What is actually happening?

```
TypeError: Cannot set property 'ts' of undefined
  at Builder.extendBuild.config (modules/typescript.js:24:33)
  at Builder.<anonymous> (node_modules/nuxt/dist/nuxt.js:155:17)
  at WebpackClientConfig.extendConfig (node_modules/nuxt/dist/nuxt.js:3126:56)
  at WebpackClientConfig.extendConfig (node_modules/nuxt/dist/nuxt.js:3258:26)
  at WebpackClientConfig.config (node_modules/nuxt/dist/nuxt.js:3164:33)
  at WebpackClientConfig.config (node_modules/nuxt/dist/nuxt.js:3292:26)
  at Builder.webpackBuild (node_modules/nuxt/dist/nuxt.js:3879:56)
  at Builder.build (node_modules/nuxt/dist/nuxt.js:3590:16)
  at <anonymous>
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/typescript-template/issues/c44">#c44</a>)</em></sub></div>

**Comment by Ataww** [comment]
Have you tried following the migration guide here? https://github.com/nuxt/nuxt.js/releases/tag/v2.0.0

I changed the import/export style of the nuxt config file and typescript module and it worked.

**Comment by P4sca1** [comment]
I changed https://github.com/nuxt-community/typescript-template/blob/master/template/nuxt.config.js#L1 to `import parseArgs from 'minimist'` and https://github.com/nuxt-community/typescript-template/blob/master/template/modules/typescript.js#L1 to `export default function() {`.
The result is the same. Am I missing something?

**Comment by Ataww** [comment]
module.exports at the bottom of nuxt.config.js need to be updated as well.

Here's how it looks like for me 
https://github.com/Ataww/typescript-template/commit/703a522627740ce9e2af143cf40ea9d77f4a123d

**Comment by P4sca1** [comment]
Your changes do not fix the issue for me. They just occur at a later state.
Also, do we really want to disable semantic checkin, as it leaves us without type checking, which is basically the point of using typescript here, isn't it?

**Comment by Ataww** [comment]
Indeed, disabling type checking is not ideal unless you want to use the [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin).

**Comment by kazumatsudo** [comment]
I had the same issue and migrated like Ataww@703a522, but didn't work.
However, I fix the following and it worked.

```
// typescript.js
for (let rule of config.module.rules) {
  if (rule.loader === "vue-loader") {
    // add this line
    rule.options.loaders = rule.options.loaders || {};
    rule.options.loaders.ts = tsLoader;
  }
}
```

I think there may be a better solution.

version
nuxt: 2.2.0
ts-loader: 5.2.2

**Comment by nicbavetta** [comment]
Has anyone been able to successfully configure TypeScript into a Nuxt 2 project?

**Comment by daveberning** [comment]
> Has anyone been able to successfully configure TypeScript into a Nuxt 2 project?

@nicbavetta I've created a [class-based Nuxt 2.x starter template with TypeScript](https://github.com/daveberning/nuxt-starter-ts). I hope this helps!

**Comment by AshleyCao** [comment]
@kazumatsudo solution works for me

**Comment by schuster-rainer** [comment]
> I had the same issue and migrated like [Ataww/typescript-template@703a522](https://github.com/Ataww/typescript-template/commit/703a522), but didn't work.
> However, I fix the following and it worked.
> 
> ```
> // typescript.js
> for (let rule of config.module.rules) {
>   if (rule.loader === "vue-loader") {
>     // add this line
>     rule.options.loaders = rule.options.loaders || {};
>     rule.options.loaders.ts = tsLoader;
>   }
> }
> ```
> I think there may be a better solution.
> 
> version
> nuxt: 2.2.0
> ts-loader: 5.2.2

I follow along and it worked.

```
npm i -g npm-check-updates
ncu -u
npm install
```

and then applying the mentioned changes.

**Comment by hmsk** [comment]
It's now running with Nuxt 2.3.4
