### ISSUE TITLE
How to use head?

### ISSUE THREAD

**Issue by fortil** [nuxt-community/typescript-template#6]
I can to see that the `registerHooks ` in  `nuxt-class-component` file, are not register the _head_ for to change the `attrs` of header

**Comment by qm3ster** [comment]
Everything you used to put in the component object can still be put into
```ts
@Component({
// IN HERE
})
export class MyComp extends Vue {
// ...
```

**Comment by AndrewBogdanovTSS** [comment]
@qm3ster when head() is place directly inside @Component is throws an error:
```
ERROR in C:\Projects\Wonder\frontend-nuxt\pages\_lang\index.vue.ts(53,3)
      TS2345: Argument of type '{ components: { Todo: typeof default; Accordion: typeof default; }; head(): { title: any; };
}' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to
write 'component'?
```
the only way head() is currently working is by placing it inside class as a regular function

**Comment by qm3ster** [comment]
@AndrewBogdanovTSS did you figure out what is happening here?
Your error also seems weird, it's complaining about an entirely different property in that object.

**Comment by AndrewBogdanovTSS** [comment]
@qm3ster as far as I understand this issue is happening because 'VueClass<Vue>' component can't be extended with "unknown " properties, and it's logical since `head` is the property that only relevant to Nuxt, not Vue, but since `nuxt-class-component` should be extending that lists of "known" properties head should be valid to be put inside anything that extends `nuxt-class-component` but that's not what's happening. So the issue is in `nuxt-class-component`

**Comment by qm3ster** [comment]
Yeah, I can see that happening, but, once again, your error actually said `components` is the problem property.

**Comment by AndrewBogdanovTSS** [comment]
@qm3ster is it? As far as I see it's arguing about the whole config object that I pass to a @Component decorator: `{ components: { Todo: typeof default; Accordion: typeof default; }; head(): { title: any; }` and it starts to happen just after I add head(): {  } property to it

**Comment by qm3ster** [comment]
> 'components' does not exist in type 'VueClass<Vue>'. Did you mean to
write 'component'
TS usually complains about one thing at a time, and we won't know what it thinks about `head` until it's satisfied with `components`
Pretty sure that the object the decorator takes for classic properties should have been extending `Vue`, not `VueClass<Vue>`.
`VueClass` is what the class **under** the decorator should be.

**Comment by dkushner** [comment]
@qm3ster You're misinterpreting the error, @AndrewBogdanovTSS is correct in this. Typescript is complaining about a type mismatch between the anonymous type described by the passed object:

```ts
{ components: { Todo: typeof default; Accordion: typeof default; }; head(): { title: any; }
```
And the expected type, `VueClass<Vue>` which is the proxy interface for exposing the properties expected on a Vue component instance. The cause of this is the fact that `head()` is obviously a feature of nuxt specifically, and not a Vue supported property.

**Comment by ibuchan72390** [comment]
For anyone else that ends up on this issue like I did.  Addition of head to your component configs is invalid due to the aforementioned typescript reasons.  The following is an invalid configuration:
```
@Component({
  head() {
    return {
      bodyAttrs: {
        class: 'layout2'
      }
    }
  }
})
export class MyComponent extends Vue {}
```

However, Nuxt is smart enough to pick up a head method in your actual class and it will treat this the same as a head method in your config.  As such, the following is valid:
```
@Component
export class MyComponent extends Vue {
   public head() {
    return {
      bodyAttrs: {
        class: 'layout2'
      }
    }
  }
}
```

**Comment by filipwronski** [comment]
In my case good solution is adding:
// index.d.ts

import Vue, { ComponentOptions } from "vue";

declare module "vue/types/options" {
  interface ComponentOptions<V extends Vue> {
    head?: here your head interface;
  }
}

**Comment by BuddhiAbeyratne** [comment]
> However, Nuxt is smart enough to pick up a head method in your actual class and it will treat this the same as a head method in your config. As such, the following is valid:

Please note that this is not the case when it comes to title head attribute, 
however [this](https://github.com/nuxt/typescript/issues/28#issuecomment-489028090) helped me

**Comment by lupas** [comment]
> In my case good solution is adding:
> 
> ```
> 
> import Vue, { ComponentOptions } from "vue";
> 
> declare module "vue/types/options" {
>   interface ComponentOptions<V extends Vue> {
>     head?: here your head interface;
>   }
> }
> ```

This did the trick for me.

**Comment by efstajas** [comment]
I ran into this problem, switched to `nuxt-property-decorator` and everything worked. Another issue if extending `vue-property-decorator`'s `Vue` is that `this` will not include modules you installed like, say, i18n or apollo which extend the main Vue instance, so `this.$i18n` would be prevented by TS for example, which after switching to `nuxt-property-decorator` no longer happened.

**Comment by helderhernandez** [comment]
hi i'm using a script (i wrote by sheer luck 😅) that allows me to declare the **_head_** outside the component and lets me use **_this_**. I repeat, the script works totally ✅, but i have the doubt if what i am doing is totally valid, can i confirm that the script is valid 🤔? the script...

```javascript
<script lang="ts">
import { Component, Vue } from "nuxt-property-decorator";
import { MetaInfo } from "vue-meta";

@Component({
  head(): MetaInfo {
    return { title: (this as ClientId).pageTitle };
  }
})
export default class ClientId extends Vue {
  pageTitle = "Edit Client";
}
</script>
```
