### ISSUE TITLE
Property 'BROWSER_BUILD' does not exist on type 'Process'.

### ISSUE THREAD

**Issue by fortil** [nuxt-community/typescript-template#7]
Hi

I have a error 
```
TS2339: Property 'BROWSER_BUILD' does not exist on type 'Process'.
```
in these code
![image](https://user-images.githubusercontent.com/6068654/27754045-f98cd51e-5dad-11e7-853e-3e7bad0b737c.png)

And when change `process.BROWSER_BUILD` for `(<any>process).BROWSER_BUILD` by `(<any>process).BROWSER_BUILD` it do another error

![image](https://user-images.githubusercontent.com/6068654/27754089-4882abb2-5dae-11e7-87e2-b245fec41e6a.png)

I don't know how to resolve..

Thanks

**Comment by qm3ster** [comment]
I'd recommend casting as
```ts
    (process as NodeJS.Process & { BROWSER_BUILD?: Boolean }).BROWSER_BUILD
// OR
    (<NodeJS.Process & { BROWSER_BUILD?: Boolean }>process).BROWSER_BUILD
```
Or much better:
```ts
interface MyProcess extends NodeJS.Process {
  BROWSER_BUILD?: boolean
}
// followed by
    (process as MyProcess).BROWSER_BUILD
// OR
    (<MyProcess>process).BROWSER_BUILD
```
As for the second error, I can't see the syntax error in the screenshot, must have been something above.
