### ISSUE TITLE
TypeScript template has error when installing in latest version

### ISSUE THREAD

**Issue by khrome83** [nuxt-community/typescript-template#78]
**NOTE** - Link to nuxtjs.cmty.io failed. Posting without using 3rd party app, please do not delete.

### Version

[v2.6.1](https://github.com/nuxt-community/typescript-template/releases/tag/v2.6.1)

### Reproduction link

Following install instructions in README.md
No other changes

### Steps to reproduce

Following install instructions in README.md
No other changes

### What is expected?

TypeScript works as expected...

### What is actually happening?

`pages/index.vue` file throws a TypeScript error - 
`@State people:Person` gives a error.

<img width="899" alt="Screen Shot 2019-04-17 at 7 12 47 AM" src="https://user-images.githubusercontent.com/1844739/56286870-71d16580-60e0-11e9-8ec2-6803c3db06a5.png">

`components/Card.vue` file throws a TypeScript error - 
`@Prop() person: Person` gives a error.

<img width="825" alt="Screen Shot 2019-04-17 at 7 12 37 AM" src="https://user-images.githubusercontent.com/1844739/56286879-7bf36400-60e0-11e9-9d43-ae4ef5523979.png">

### Additional comments?

The code is copied and pasted exactly.

**Comment by khrome83** [comment]
@hmsk - this is a bug, cmty link failed, I copied the format from another submission on nuxt website.

**Comment by donPuerto** [comment]
same here. Any resolve?

**Comment by khrome83** [comment]
@donPuerto - I can't remember if I tried a different template, or if I just needed to use `@Prop() person !: Person`, notice the `!` missing from my examples before.
