### ISSUE TITLE
Fresh Installed and got this error

### ISSUE THREAD

**Issue by donPuerto** [nuxt-community/typescript-template#89]
![image](https://user-images.githubusercontent.com/9329005/57969909-42e33380-79ad-11e9-9af9-22e0a88f9712.png)
Any idea?

**Comment by hmsk** [comment]
Probably, your Vuex in node_modules is older unntentionally. I saw similar errors in my projects. Try to remove node_modules, package-lock.json (or yarn.lock) then re-run npm/yarn install. (Or install the latest Vuex explicitly)
