### ISSUE TITLE
Will you add express to your template?

### ISSUE THREAD

**Issue by NIM-Pro** [nuxt-community/typescript-template#9]
I mean [~server/index.js](https://github.com/nuxt-community/express-template/blob/master/template/server/index.js), like in [nuxt-community/express-template](https://github.com/nuxt-community/express-template). This would be very useful for starting the development of a more complex application than a simple catalog of personalities.
Will you?

**Comment by DavidBernal** [comment]
You can see my repo: 
https://github.com/DavidBernal/typescript-express-decorators-template
Is nuxt + typescript + decorators + expressjs
PR are welcome.

**Comment by NIM-Pro** [comment]
Great, I will!
Thank you for your contribution to lowering the input threshold for beginners _:)_
